logging:
  level:
    io.lettuce.core: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  redis:
    # redis分片集群(多主多从)
    cluster:
      # 集群的所有节点
      nodes:
        - 10.190.67.128:7001
        - 10.190.67.128:7002
        - 10.190.67.128:7003
        - 10.190.67.128:8001
        - 10.190.67.128:8002
        - 10.190.67.128:8003
#    # 配置redis哨兵
#    sentinel:
#      # 主节点名称
#      master: mymaster
#      # 哨兵节点地址
#      nodes:
#        - 10.190.67.128:27001
#        - 10.190.67.128:27002
#        - 10.190.67.128:27003